site_name: ""
site_url: https://docs.productscience.app
repo_url: https://docs.productscience.app
edit_uri: edit/main/docs
copyright: Copyright Product Science Inc. All rights reserved.
site_description: >-
  Learn to configure and use Product Science

# Content
nav:
  - Home: index.md
  - Integration:
      - Android:
          - Build / Gradle: android/gradle.md
          - CICD / Gradle: android/cicd.md
          - CLI Tool: android/cli-tool.md
          - Integration FAQ: android/integration-faq-android.md
          - User Flow Annotation: android/user-flow.md
      - iOS:
          - Build / Xcode: ios/xcode.md
          - Build / Bazel: ios/bazel.md
          - App Distribution: ios/distribution.md
  - Device Set-Up:
      - Android: website-docs/device-set-up-android.md
      - iOS: website-docs/device-set-up-ios.md
  - Record + Upload:
      - Anroid: website-docs/record-n-upload-android.md
      - iOS: website-docs/record-n-upload-ios.md

# Visual
theme:
  name: material
  custom_dir: overrides
  logo: images/logo-text.svg
  favicon: images/Icon.png
  font:
    text: Manrope
  palette:
    # Light mode
    # media: "(prefers-color-scheme: light)"
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  include_search_page: false
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - navigation.indexes
    - navigation.tracking
    - search.suggest
#    - toc.integrate

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - toc
  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

plugins:
  - minify:
      minify_html: false
  - search
  - macros:
      modules: ["ps-plugin"]
  - mkdocs-video:
      is_video: true
      video_muted: true
      video_controls: true
      css_style:
        width: "50%"

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/product-science-inc/
