name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3 ⚙️ 🐍
        uses: actions/setup-python@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/buildtools/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        working-directory: 'docs/buildtools'
        run: sh ./mkdocs-setup.sh

      - name: Build and deploy to GitHub Pages
        working-directory: docs
        run: mkdocs build

      - name: Checkout Deploy Repo
        uses: actions/checkout@v3
        with:
          repository: product-science/product-science.github.io
          ref: master
          path: product-science.github.io
          token: ${{ secrets.PS_GITHUB_TOKEN }}

      - name: Deploy web site
        working-directory: 'product-science.github.io'
        run: sh ../docs/buildtools/io-deploy.sh
